ktor:
    application:
        modules:
            - developidea.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: $jwtAudience
  realm: $jwtRealm
  issuer: $jwtIssuer
  secret: $jwtSecret

db:
  mongo:
    username: $mongoUsername
    password: $mongoPassword
    host: $mongoHost
