ktor:
    application:
        modules:
            - developidea.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

db:
  mongo:
    username: $mongoUsername
    password: $mongoPassword
    host: $mongoHost
