ktor:
    application:
        modules:
            - developidea.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  audience: $jwtAudience
  realm: $jwtRealm
  issuer: $jwtIssuer
  secret: $jwtSecret

db:
  mongo:
    user: $mongoUser
    password: $mongoPassword
    host: $mongoHost
    database:
      name: $mongoDatabaseName
